version: "3.8"

services:
  frontend:
    build: .
    container_name: cloudpulse_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.evn
    depends_on:
      - backend 
    restart: always

  backend:
    build: ./backend
    container_name: cloudpulse_backend 
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - minio
    volumes:
      - ./backend:/app
    restart: always

  minio:
    image: minio/minio
    container_name: cloudpulse-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./backend/.env
    volumes:
      - ~/minio-data:/data
    command: server /data --console-address ":9001"
    restart: always
